### PR TITLE
enh: Possibility to perform relative resampling of images

### PR DESCRIPTION
**Pull request by stefanpsz**
I came across the necessity of being able to specify the resampling of images in a registration as being done in a relative way, i.e., the resampling is proportional to the voxel size of the image in each direction.

In this particular implementation, this is done by adding a flag parameter "Relative Resolution(s)" which indicates whether the resampling is indeed done in a relative way or not. Additionally, the values specified in the "Resolution" parameter will be treated as factors of the voxel size in each direction if this flag is set to "Yes/True". For example, for an image with voxel size 0.4x0.4x2 the resolution parameter "2 2 1" means that the image must be resampled in a 0.8x0.8x2 grid instead of a 2x2x1 one, if the "Relative Resolution(s)" flag is set to "Yes/True"

### CODE REVIEW

**Comment by schuhschuh** [comment]
Thanks @stefanpsz. That's useful and a quite straightforward modification.

However, could I convince you to modify this to not require an additional parameter? I am thinking of the ability to specify the units in which the numbers are given either in square brackets as suffix of the parameter name or as suffix without square brackets of the parameter value string, i.e.,

```
Resolution [abs] = 2 2 1
Resolution [mm] = 2 2 1
Resolution = 2 2 1 mm
Resolution = 2 mm
```

vs.

```
Resolution [rel] = 2 2 1
Resolution [vox] = 2 2 1
Resolution = 2 2 1 vox
Resolution = 2 vox
Resolution [%] = 200 200 100
Resolution = 200 200 100 %
```
where ```2 vox``` means that each voxel of the resampled image spans 2 voxels of the input image in that dimension. I have done something similar for the window size of the LNCC similarity measure.

Same for the ```Blurring``` parameter.

**Comment by ghisvail** [comment]
I like the [mm] and [%] qualifiers, they are explicit which is good from the user's POV.

**Comment by stefanpsz** [comment]
> could I convince you to modify this to not require an additional parameter?

Of course you can. I have to say though, that I cannot really commit on a time this will be ready. As soon as I find the time, I will look at it.

**Comment by stefanpsz** [comment]
Updated :)

**Comment by schuhschuh** [comment]
Thanks, a few minor points and one refactoring wish.
- Code indentation is inconsistent.
- As noted in the commit, the conversion from relative to absolute units should be done in ```GuessParameters``` before the ```_Resolution``` values are being used.

Refactoring:
- Global auxiliary functions in the Common module can be shared between all code that parses parameters (which is part of the ```mirtk::Object``` model, i.e., common to all objects). I've added these auxiliary functions and use them for the LNCC (see PR #93). These can be used for the resolution parameter parsing as follows:
```c++
bool GenericRegistrationFilter::Set(const char *param, const char *value, int level)
{
  string name, type, value, units;
  type  = ParameterUnits(param, &name);
  units = ValueUnits(value);

  if (name == "Resolution") {

    // Make parameter and value units consistent or return false in case of mismatch
    if      (units == "rel") units = "vox";
    else if (units == "abs") units = "mm";
    if (type.empty()) {
      if (units.empty()) type = units = "signed";
      else type = units;
    } else {
      if      (type == "rel") type = "vox";
      else if (type == "abs") type = "mm";
    }
    if (type != units) return false;

    // Parse and convert resolution values to signed values (pos: mm, neg: vox)
    double dx = .0, dy = .0, dz = .0;
    int n = sscanf(value, "%lf %lf %lf", &dx, &dy, &dz);
    if (n == 0) return false;
    if (n == 1) dz = dy = dx;
    if (units != "signed") {
      if (dx < .0 || dy < .0 || dz < .0) return false;
      if (units == "vox") {
        dx = -dx, dy = -dy, dz = -dz;
      } else if (units == "%") {
        dx = - (dx / 100.0);
        dy = - (dy / 100.0);
        dz = - (dz / 100.0);
      }
    }
    _Resolution[level] = Vector3D<double>(dx, dy, dz);
    return true;
  }
  return false;
}
```
This should simplify the implementation and not require the use of ```strncmp``` and ```strstr```. Moreover, the same concept of units specification as part of either the parameter name or the value is unified across registration components.

**Comment by schuhschuh** [comment]
BTW I think for "resolution" it would make sense when 50% corresponds to half the resolution, ie, twice the voxel size:

```
Resolution = 2 vox
Resolution = 50%
```
being equivalent. ```dx = - 100/dx``` to convert from percentage to voxel units.

**Comment by stefanpsz** [comment]
> BTW I think for "resolution" it would make sense when 50% corresponds to half the resolution, ie, twice the voxel size

Done

**Comment by schuhschuh** [comment]
Rejecting this PR. The suggested changes have been merged as new PR #175.

@stefanpsz Consider discarding your feature branch (```git branch -D stefanpsz:enh/relative-resampling```) and pull the merged changes from the ```develop``` branch. Let me know if it doesn't work as expected/intended.

**Comment by ghisvail** [comment]
Although it is nice that this issue is now resolved, it is considered bad etiquette to short-circuit work started by a contributor (here @stefanpsz). In the future, please consider letting the contributor refine the PR proposal based on your review, rather than merging your own changes in, thereby dropping any form of credit. Thanks.

**Comment by schuhschuh** [comment]
Thanks for the lesson about etiquette. @stefanpsz asked me to finalise this change which does not contain any of his code modifications. So I don't see an issue about credits here.

**Comment by ghisvail** [comment]
Never mind then.

**Pull request closed without merging**
