### PR TITLE
adding Draw-EM submodule

### PR DESCRIPTION
**Pull request by amakropoulos**
This change is [Reviewable](https://reviewable.io/reviews/biomedia/mirtk/279)

### CODE REVIEW

**Comment by schuhschuh** [comment]
When I merge this it probably reverts the other fix of Histogram1D. Could you modify the PR to only include the last commit? Possibly using git rebase, or creating a new branch and git cherry-pick only the one commit. Then force push the changes to the branch of thus PR.

**Comment by schuhschuh** [comment]
@amakropoulos You could actually just force push the commits from a new local branch to the @amakropoulos:DrawEM-submodule remote branch without the two "typo" and "back" commits. No problem to modify a PR after it was submitted.

**Comment by schuhschuh** [comment]
I'll manually merge the one commit that adds the Draw-EM module when I pushed some of my local changes, possibly tomorrow morning.

**Comment by amakropoulos** [comment]
Did this fix it? The git stuff seems Chinese (not Greek :)) to me.
Otherwise I'm thinking of closing this, pull the master and redo the 2 changes..

**Comment by schuhschuh** [comment]
Yes, it would fix it somehow. However, we prefer to keep PR's clean, i.e., without commits and reverted commits and also without merge commits. For this, you need to use `git rebase`. Don't worry about it. I'll modify the history of this PR myself and before I merge it.

**Comment by amakropoulos** [comment]
:) thanks

**Comment by schuhschuh** [comment]
Manually merged PR with commit 654558297d37a86e912a2c9cd9519d159ddb6518.

**Comment by schuhschuh** [comment]
PS: Seems the PR was missing a commit, the file `Packages/DrawEM` is missing. @amakropoulos Adding a submodule is done with the `git submodule add` command. Manually editing the file `.gitmodules` is not sufficient... fixing it now.

**Comment by amakropoulos** [comment]
great thanks!

**Pull request closed without merging**
