### PR TITLE
bug in LCC label output

### PR DESCRIPTION
**Pull request by amakropoulos**
This change is [Reviewable](https://reviewable.io/reviews/biomedia/mirtk/374)

### CODE REVIEW

**Comment by schuhschuh** [comment]
Indeed, that's a mistake. However, I think the fix should be to relabel the resulting filtered labels again, such that the output has monotone increasing labels starting with 1.

```c++
  int output_label = 0;
  UnorderedMap<int, int> component_labels;
  for (int component_label = min_label; component_label <= max_label; ++component_label) {
    int size = cc.ComponentSize(component_label);
    if (min_size <= size && size <= max_size) {
      component_labels.insert(MakePair(component_label, ++output_label));
    }
  }

  // ...

  if (output_type == ComponentLabels) {
      for (int idx = 0; idx < output.NumberOfVoxels(); ++idx) {
        component_label = cc.Output()->Get(idx);
        auto component = component_labels.find(component_label);
        if (component != component_labels.end()) {
          output(idx) = component->second;
        }
      }
  }
```

**Comment by schuhschuh** [comment]
Can you also please remove the update of the Draw-EM module commit from this PR? It seems that is causing a conflict because I recently committed a similar change.

**Comment by amakropoulos** [comment]
Sorry, how can I do that?

**Comment by schuhschuh** [comment]
Try  `git rebase 49d6eeee0eb9ef7939f117b0697e05edf060e403` and then re-commit the bug fix for `extract-connected-components` only. Followed by `git push -f`.

**Comment by schuhschuh** [comment]
`git reset` actually, not `git rebase`...

**Comment by amakropoulos** [comment]
thanks!

**Pull request merged**
