### PR TITLE
enh: project-onto-surface

### PR DESCRIPTION
**Pull request by amakropoulos**
Allows to project scalars from another surface according to the closest points

---
This change is [Reviewable](https://reviewable.io/reviews/biomedia/mirtk/351)

### CODE REVIEW

**Comment by schuhschuh** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Applications/src/project-onto-surface.cc, line 91 \[r1\]](https://reviewable.io:443/reviews/biomedia/mirtk/351#-KNCqD6Fs1Hcp9jKXoiE:-KNCqD6Fs1Hcp9jKXoiF:-508415977) ([raw file](https://github.com/biomedia/mirtk/blob/2de6384bfc8edae1ff15e84d9ef5848f08b0e90e/Applications/src/project-onto-surface.cc#L91)):*
> ```cpp
>   cout << "  -min-size <n>              Surface patches with less than n points are removed. (default: 0)\n";
>   cout << "  -surface <file>            Input surface from which to project scalars.\n";
>   cout << "  -scalars <name> [<name2>]  Scalars to be projected from the input surface (can be defined multiple times). \n";
> ```

Can you please modify this to ensure that either 3 space characters are between `-scalars <name> [<name2>]' and the description or, better in case of long option arguments, add a newline as follows:

```c++
cout << "  -scalars <input_name> [<output_name>]\n";
cout << "      Scalars to be projected from the input surface (can be defined multiple times).\n";
cout << "      The name of the array in the output file is <output_name>, which defaults to\n";
cout << "      the <input_name> of the data array if not specified.\n";
```

The minimum of 3 spaces between arguments and description in the help output is due to the `help-rst` tool that converts the output to reStructuredText for the HTML help page generation for the command.

---

*[Applications/src/project-onto-surface.cc, line 1167 \[r1\]](https://reviewable.io:443/reviews/biomedia/mirtk/351#-KNCrN5FVmjjrPym1lHT:-KNCrN5FVmjjrPym1lHU:-1378422650) ([raw file](https://github.com/biomedia/mirtk/blob/2de6384bfc8edae1ff15e84d9ef5848f08b0e90e/Applications/src/project-onto-surface.cc#L1167)):*
> ```cpp
>     }
>   } else if (input_surface_proj_name) {
>     if (surface_proj_input_scalars_names.size() == 0)
> ```

I would use `surface_proj_input_scalars.empty()`. But also, when this is the case, I would use the default scalars of the surface mesh, i.e., `surface_proj->GetPointData()->GetScalars()`. Only when this returns `nullptr`, I would raise an error that the surface has no default scalar data and therefore `-scalars` option is required. You will thus have to check this later when you actually read the surface from file.

---

*[Applications/src/project-onto-surface.cc, line 1456 \[r1\]](https://reviewable.io:443/reviews/biomedia/mirtk/351#-KNCskbme92MtwBQ7OFd:-KNCskbnuvBgbLbkRiO3:-866376278) ([raw file](https://github.com/biomedia/mirtk/blob/2de6384bfc8edae1ff15e84d9ef5848f08b0e90e/Applications/src/project-onto-surface.cc#L1456)):*
> ```cpp
> 
>     const vtkIdType noOfPoints = surface->GetNumberOfPoints();
>     for(int a=0; a<surface_proj_input_scalars_names.size(); a++){
> ```

Please use type `size_t` for loop variable `a` because that is the unsigned type returned by `surface_proj_input_scalars_names.size()`. Many compilers will complain about comparison of signed and unsigned values otherwise. And while you're at it, how about `++a` ? Makes no difference here, but good to have a common "standard" for incrementing "iterators". And prefix increment is more efficient than postfix increment for STL iterators. I also like spaces for better readability.

So all in all:
```c++
for (size_t a = 0; a < surface_proj_input_scalars_names.size(); ++a) {
```

---

*[Applications/src/project-onto-surface.cc, line 1458 \[r1\]](https://reviewable.io:443/reviews/biomedia/mirtk/351#-KNCsMdtLaiwNKmaj3nP:-KNCsMdtLaiwNKmaj3nQ:-1707620221) ([raw file](https://github.com/biomedia/mirtk/blob/2de6384bfc8edae1ff15e84d9ef5848f08b0e90e/Applications/src/project-onto-surface.cc#L1458)):*
> ```cpp
>     for(int a=0; a<surface_proj_input_scalars_names.size(); a++){
>       vtkDataArray* source_array = surface_proj->GetPointData()->GetArray(surface_proj_input_scalars_names[a]);
>       vtkSmartPointer<vtkDataArray> array = vtkSmartPointer<vtkDataArray>::NewInstance(source_array);
> ```

Good! I made the mistake often to assign `source_array->NewInstance()` and cause memory leaks.

But if you don't mind, I prefer the notation:
```c++
vtkSmartPointer<vtkDataArray> array;
array.TakeReference(source_array->NewInstance());
```
because the template argument `vtkDataArray` appears only once and it is also more obvious that a (virtual) function on `source_array` object is called.

---

*[Applications/src/project-onto-surface.cc, line 1460 \[r1\]](https://reviewable.io:443/reviews/biomedia/mirtk/351#-KNCrytblglNzXMB5aZV:-KNCrytcUNGpFdDlYk9k:-1578976304) ([raw file](https://github.com/biomedia/mirtk/blob/2de6384bfc8edae1ff15e84d9ef5848f08b0e90e/Applications/src/project-onto-surface.cc#L1460)):*
> ```cpp
>       vtkSmartPointer<vtkDataArray> array = vtkSmartPointer<vtkDataArray>::NewInstance(source_array);
>       array->SetName(surface_proj_output_scalars_names[a]);
>       array->SetNumberOfComponents(1);
> ```

What if the input array has multiple components? Shouldn't that be fine, too?
```c++
array->SetNumberOfComponents(source_array->GetNumberOfComponents());
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/biomedia/mirtk/351)*

**Comment by schuhschuh** [comment]
@amakropoulos Your last commit a8204bd to this feature branch seems to have reverted the previous addition of the `-surface` option to `project-onto-surface`. Was this really intented?

**Comment by amakropoulos** [comment]
No, sorry. How do I revert back to the previous one?
I will move the new changes at a separate branch/pull request.

**Comment by schuhschuh** [comment]
You can create a new branch and cherry-pick this last commit first to preserve the changes:
```shell
git branch master enh-project-labels-onto-surface
git checkout enh-project-labels-onto-surface
git cherry-pick a8204bd
```
Then you can go back to this feature branch and reset it to the previous commit:
```shell
git checkout project-onto-surface
git reset --hard a40c203
git push -f
```

**Comment by amakropoulos** [comment]
great, thanks!

**Comment by schuhschuh** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Applications/src/project-onto-surface.cc, line 1462 \[r3\]](https://reviewable.io:443/reviews/biomedia/mirtk/351#-KNh6720I5CzRfVF_BXj:-KNh6720I5CzRfVF_BXk:-524353353) ([raw file](https://github.com/biomedia/mirtk/blob/a40c2036f9dc231b36f34b33f85d17a21c8a6d9f/Applications/src/project-onto-surface.cc#L1462)):*
> ```cpp
> 
>     const vtkIdType noOfPoints = surface->GetNumberOfPoints();
>     for (size_t a = 0; a < surface_proj_input_scalars_names.size(); ++a) {
> ```

Just FYI, no need to change.

With C++11, we can now write:
```c++
for (auto name : surface_proj_input_scalars_names) {
  // [...]
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/biomedia/mirtk/351)*

**Pull request merged**
